import Validator from "validator";
import bcrypt from "bcrypt";
import userModel from "../models/userModel.js";
import jwt from "jsonwebtoken";
import { v2 as cloudinary } from "cloudinary";
import doctorModel from "../models/doctorModel.js";
import appointmentModel from "../models/appointmentModel.js";
import razorpay from "razorpay";

// Api to regester user

const registerUser = async (req, res) => {
  try {
    const { name, email, password } = req.body;
    if (!name || !email || !password) {
      return res.json({ success: false, message: "All fields are required" });
    }
    // validating email
    if (!Validator.isEmail(email)) {
      return res.json({ success: false, message: "Invalid email address" });
    }
    //validating password
    if (password.length < 8) {
      return res.json({
        success: false,
        message: "Password must be atleast 8 characters long",
      });
    }
    // hashing user password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    const userData = {
      name,
      email,
      password: hashedPassword,
    };
    // saving user data to database
    const newUser = new userModel(userData);
    const user = await newUser.save();
    
    // _id is automatically generated by mongodb

    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET);
    res.json({ success: true, token });
  } catch (error) {
    res.json({ success: false, message: error.message });
  }
};

// Api to login user

const loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email) {
      return res.json({ success: false, message: "All fields are required" });
    }
    if(!password){
      return res.json({ success: false, message: "Please enter a password" });
    }

    const user = await userModel.findOne({ email });

    if (!user) {
      return res.json({ success: false, message: "User not found" });
    }
    const isMatch = await bcrypt.compare(password, user.password);
    if (isMatch) {
      const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET);
      res.json({ success: true, token });
    } else {
      res.json({ success: false, message: "Invalid Password" });
    }
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};

//Api to get user data

const getProfile = async (req, res) => {
  try {
    
    const { userId } = req.body
    const userData = await userModel.findById(userId).select("-password");
    res.json({ success: true, userData });

  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
    
  }
}

//API to update user profile

const updateProfile = async (req, res) => {
  try {
    
    const { userId, name, phone, address, dob, gender} = req.body
    const imageFile = req.file

    if(!name || !phone || !dob){
      return res.json({ success: false, message: "All fields are required" });
    }

    await userModel.findByIdAndUpdate(userId, { name, phone, address:JSON.parse(address), dob, gender})
    
    if(imageFile){
      
      // uploading image to cloudinary
      const imageUpload = await cloudinary.uploader.upload(imageFile.path, { resource_type: "image" });
      const imageURL = imageUpload.secure_url;

      await userModel.findByIdAndUpdate(userId, { image: imageURL })
    }
    res.json({ success: true, message: "Profile updated successfully" });

  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
}

//API to book appointment

const bookAppointment = async (req, res) => {
  try {

    const { userId, docId, slotDate, slotTime } = req.body

    const docData = await doctorModel.findById(docId).select("-password");

    if(!docData.available){
      return res.json({ success: false, message: "Doctor is not available" });
    }

    let slots_booked = docData.slots_booked

    // checking if slot is already booked
    if(slots_booked[slotDate]){
      if(slots_booked[slotDate].includes(slotTime)){
        return res.json({ success: false, message: "Slot is already booked" });
      }else{
        slots_booked[slotDate].push(slotTime)
      }
    }else{
      slots_booked[slotDate] = []
      slots_booked[slotDate].push(slotTime)
    }

    const userData = await userModel.findById(userId).select("-password");
    delete docData.slots_booked

    const appointmentData = {
      userId,
      docId,
      slotDate,
      slotTime,
      userData,
      docData,
      amount: docData.fees,
      date: Date.now()
    }
    const newAppointment = new appointmentModel(appointmentData);
    await newAppointment.save();

    //save new slots data to docData

    await doctorModel.findByIdAndUpdate(docId, { slots_booked })

    res.json({ success: true, message: "Appointment booked successfully" });
    
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
}

//API to get user appointments for my-appointments page

const listAppointments = async (req, res) => {
  try {

    const { userId } = req.body
    const appointments = await appointmentModel.find({ userId })

    res.json({ success: true, appointments });
    
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
    
  }
}

//API to cancel appointment

const cancelAppointment = async (req, res) => {
  try {

    const { userId, appointmentId } = req.body
    const appointmentData = await appointmentModel.findById(appointmentId)
    
    //Verify appointment belongs to user
    if(appointmentData.userId !== userId){
      return res.json({ success: false, message: "Unauthorized access" });
    }

    await appointmentModel.findByIdAndUpdate(appointmentId, { cancelled: true })

    // Releasing doctor slot
    const { docId, slotDate, slotTime } = appointmentData
    const docData = await doctorModel.findById(docId).select("-password");

    let slots_booked = docData.slots_booked
    slots_booked[slotDate] = slots_booked[slotDate].filter( e => e !== slotTime)
    await doctorModel.findByIdAndUpdate(docId, { slots_booked })

    res.json({ success: true, message: "Appointment cancelled successfully" });
    
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
    
  }
}


// API for eSewa payment
const paymentEsewa = async (req, res) => {
  try {
    const { appointmentId } = req.body;
    
    const appointmentData = await appointmentModel.findById(appointmentId);
    
    if (!appointmentData || appointmentData.cancelled) {
      return res.json({ success: false, message: "Appointment not found or cancelled" });
    }
    
    // eSewa payment parameters
    const esewaPaymentData = {
      amount: appointmentData.amount,
      tax_amount: 0,
      total_amount: appointmentData.amount,
      transaction_uuid: appointmentId,
      product_code: "EPAYTEST", // Use your eSewa merchant code
      product_service_charge: 0,
      product_delivery_charge: 0,
      success_url: `${process.env.FRONTEND_URL}/verify-payment`,
      failure_url: `${process.env.FRONTEND_URL}/my-appointments`,
      signed_field_names: "total_amount,transaction_uuid,product_code",
    };

    res.json({ success: true, paymentData: esewaPaymentData });
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};

// API to verify eSewa payment
const verifyEsewa = async (req, res) => {
  try {
    const { appointmentId, oid, amt, refId } = req.body;

    // Verify payment with eSewa
    // In production, you would verify with eSewa server
    
    const appointmentData = await appointmentModel.findById(appointmentId);
    
    if (appointmentData && !appointmentData.payment) {
      await appointmentModel.findByIdAndUpdate(appointmentId, { 
        payment: true,
        status: "Accepted"
      });
      res.json({ success: true, message: "Payment successful" });
    } else {
      res.json({ success: false, message: "Payment verification failed" });
    }
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};


export { registerUser, loginUser, getProfile, updateProfile, bookAppointment, listAppointments, cancelAppointment, paymentEsewa, verifyEsewa };
